### ISSUE TITLE
Support YAML-based configuration for custom rules engine

### ISSUE THREAD

**Issue by anubhavg-icpl** [anubhavg-icpl/AppleEndpointSecurityC#1]
Currently the example hard-codes a single rule (blocking `/etc/passwd` opens). To make the client extensible, we should load rules from a YAML configuration file at startup and drive the ES event callback from that. This would allow users to define custom event–path–action mappings without recompiling, for example:

```yaml
# config/rules.yml
rules:
  - event: ES_EVENT_TYPE_AUTH_OPEN
    path: "/etc/passwd"
    action: block
  - event: ES_EVENT_TYPE_NOTIFY_WRITE
    path_regex: "^/var/log/.*\\.log$"
    action: allow
  - event: ES_EVENT_TYPE_AUTH_UNLINK
    path: "/tmp/secrets.txt"
    action: block
  - event: ES_EVENT_TYPE_NOTIFY_OPEN
    path: "/usr/local/bin/custom"
    action: log
```

**Proposed changes:**
1. **Dependency**: Introduce a lightweight YAML parser (e.g., [[libyaml](https://github.com/yaml/libyaml)](https://github.com/yaml/libyaml) or [[yaml-c-cpp](https://github.com/jbeder/yaml-cpp)](https://github.com/jbeder/yaml-cpp)) in `Makefile`.
2. **Config loader**: At startup, read `config/rules.yml` into an in-memory rule list.
3. **Rule struct**: Define a `struct rule { es_event_type_t event; regex_t path_regex; enum { ALLOW, BLOCK, LOG } action; }`.
4. **Callback engine**: Replace the existing `strncmp` check with:
   - Iterate loaded rules  
   - If `msg->event_type == rule.event` and the file path matches `rule.path_regex`, respond using `es_respond_flags_result()` based on `rule.action`.  
   - If no rules match, default to “allow”.
5. **Example**: Provide a sample `rules.yml` and document how to extend it.

**Benefits:**
- No more recompilation for new rules  
- Flexible multi-rule support (regex, multiple events)  
- Easier for users to customize in production

Please let me know if any tweaks are needed or if you’d like to see a more detailed design. I’d be happy to help with a PR!
